CREATE TABLE `s_sso_server_auth_code` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `uid` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `livestatus` enum('0','1','2','3') COLLATE utf8mb4_unicode_ci DEFAULT '0' COMMENT '0 = inactive, 1 = active, 2 = archived, 3 = suspended',
  `versioncode` int(11) DEFAULT NULL,
  `wf_status` int(11) NOT NULL DEFAULT '0',
  `space_id` bigint(20) NOT NULL DEFAULT '0',
  `createdby` bigint(20) DEFAULT NULL,
  `createstamp` datetime DEFAULT NULL,
  `updatedby` bigint(20) DEFAULT NULL,
  `updatestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `s_code_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `s_client_id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `s_entity_id` bigint(20) NOT NULL DEFAULT '0',
  `s_redirect_uri` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `s_email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `s_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `s_sub` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `s_nonce` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `s_scope` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `s_code_challenge` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `s_integration_level` enum('verify_only','full_integration') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'verify_only',
  `s_expires_at` datetime NOT NULL,
  `s_consumed_at` datetime DEFAULT NULL,
  `s_client_ip` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uid` (`uid`),
  UNIQUE KEY `uniq_code_hash` (`s_code_hash`),
  KEY `idx_client_live` (`s_client_id`,`livestatus`),
  KEY `idx_entity_live` (`s_entity_id`,`livestatus`),
  KEY `idx_expires_at` (`s_expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `s_sso_server_access_token` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `uid` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `livestatus` enum('0','1','2','3') COLLATE utf8mb4_unicode_ci DEFAULT '0' COMMENT '0 = inactive, 1 = active, 2 = archived, 3 = suspended',
  `versioncode` int(11) DEFAULT NULL,
  `wf_status` int(11) NOT NULL DEFAULT '0',
  `space_id` bigint(20) NOT NULL DEFAULT '0',
  `createdby` bigint(20) DEFAULT NULL,
  `createstamp` datetime DEFAULT NULL,
  `updatedby` bigint(20) DEFAULT NULL,
  `updatestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `s_token_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `s_client_id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `s_entity_id` bigint(20) NOT NULL DEFAULT '0',
  `s_sub` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `s_email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `s_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `s_scope` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `s_integration_level` enum('verify_only','full_integration') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'verify_only',
  `s_expires_at` datetime NOT NULL,
  `s_revoked_at` datetime DEFAULT NULL,
  `s_client_ip` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uid` (`uid`),
  UNIQUE KEY `uniq_token_hash` (`s_token_hash`),
  KEY `idx_client_live` (`s_client_id`,`livestatus`),
  KEY `idx_entity_live` (`s_entity_id`,`livestatus`),
  KEY `idx_expires_at` (`s_expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
