-- Safe Community Edition seed data.
-- This file intentionally does not create users, password hashes, API keys, provider secrets, IP allowlists, or private URLs.

INSERT INTO `s_config` (`uid`, `livestatus`, `wf_status`, `space_id`, `updatestamp`, `s_config_handle`, `s_config_value`, `s_config_origin`, `s_description`) VALUES
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'project_title', 'Batoi RAD Application', 'S', 'Application title.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'author', 'Batoi', 'S', 'Application author or organization.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'base_url', 'http://localhost', 'S', 'Base URL for the application.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'allowed_ips', '127.0.0.1,::1', 'S', 'Comma-separated admin IP allowlist.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'timezone', 'UTC', 'S', 'Default timezone.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'locale', 'en_US', 'S', 'Default locale.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'currency', 'USD', 'S', 'Default currency.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'country', 'US', 'S', 'Default country.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'session_name', 'batoi_rad_session', 'S', 'PHP session name.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'session_lifetime', '1800', 'S', 'Session lifetime in seconds.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'session_path_default', 'N', 'S', 'Use PHP default session path.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'session_domain', '', 'S', 'Session cookie domain.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'session_secure', '0', 'S', 'Require secure session cookie.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'session_httponly', '1', 'S', 'Use HTTP-only session cookie.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'display_errors', 'false', 'S', 'Display PHP errors.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'site_status', 'L', 'S', 'Site status.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'ip_access_restrict', 'N', 'S', 'Restrict RAD Admin by IP allowlist.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'site_update_pending', 'N', 'S', 'Site update pending flag.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'enable_sql_log', 'false', 'S', 'Enable SQL logging.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'encryption_method', 'AES-256-CBC', 'S', 'Encryption method.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'home_dashboard_cache_ttl', '120', 'S', 'Home dashboard cache TTL in seconds.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'rad_admin_uif_enabled', 'Y', 'S', 'Enable Batoi UIF assets in RAD Admin.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'public_theme_uif_enabled', 'Y', 'S', 'Enable Batoi UIF assets in public runtime themes.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'rad_admin_monaco_base_url', '', 'S', 'Self-hosted Monaco editor base URL for RAD Admin code editors.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'rad_admin_community_edition', 'Y', 'S', 'Hide and block held-back RAD Admin modules in Community Edition.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'dev_debug_flag', 'N', 'S', 'Show developer debug output.');

INSERT INTO `s_role` (`uid`, `livestatus`, `wf_status`, `space_id`, `updatestamp`, `s_role_name`, `s_default_route_id`, `s_scope`, `s_code`, `s_ms_id`, `s_description`) VALUES
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'Administrator', NULL, 'platform', 'system_admin', NULL, 'Default platform administrator role.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'Manager', NULL, 'workspace', 'manager', NULL, 'Default workspace manager role.'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'Member', NULL, 'workspace', 'member', NULL, 'Default workspace member role.');

INSERT INTO `s_data_field_type` (`uid`, `livestatus`, `wf_status`, `space_id`, `updatestamp`, `s_name`, `s_description`, `s_definition`) VALUES
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'TEXT_BOX', 'Single-line text box', '{"input_type":"text"}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'EMAIL', 'Email field', '{"input_type":"email","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'URL', 'URL field', '{"input_type":"url","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'PASSWORD', 'Password field', '{"input_type":"password","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'NUMBER', 'Number field', '{"input_type":"number","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'DECIMAL', 'Decimal number field', '{"input_type":"decimal","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'PHONE', 'Phone number field with country code', '{"input_type":"phone","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'PHONE_NO_CC', 'Phone number field without country code', '{"input_type":"phone_no_cc","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'MONEY', 'Money field with currency code', '{"input_type":"money","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'MONEY_NO_CC', 'Money field without currency code', '{"input_type":"money_no_cc","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'PERCENTAGE', 'Percentage field', '{"input_type":"percentage","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'SINGLE_LINE_ENCRYPTED_TEXT', 'Single-line encrypted text box', '{"input_type":"single_line_encrypted_text","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'MULTI_LINE_ENCRYPTED_TEXT', 'Multi-line encrypted text box', '{"input_type":"multi_line_encrypted_text","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'AUTO_SUGGEST', 'Auto-suggest text box', '{"input_type":"auto_suggest","source":"remote_or_local_data_source"}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'TEXT_AREA', 'Multi-line text box', '{"input_type":"textarea"}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'RICH_TEXT', 'Rich text box', '{"input_type":"rich_text"}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'DROPDOWN', 'Dropdown field', '{"input_type":"enum","options":["Option 1","Option 2"]}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'SINGLE_CHECKBOX', 'Single checkbox field', '{"input_type":"single_checkbox"}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'MULTI_CHECKBOX', 'Multi-checkbox field', '{"input_type":"multi_checkbox","options":["Option 1","Option 2","Option 3"]}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'MULTI_SELECT', 'Multi-select field', '{"input_type":"multi_select","options":["Option 1","Option 2","Option 3"]}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'RADIO_BUTTON', 'Radio button field', '{"input_type":"radio","options":["Option 1","Option 2"]}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'RADIO_YES_NO', 'Yes/no radio field', '{"input_type":"radio","options":["Yes","No"]}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'DATE_PICKER', 'Date picker field', '{"input_type":"date"}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'TIME_PICKER', 'Time picker field', '{"input_type":"time_picker","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'DATE_RANGE', 'Date range field', '{"input_type":"date_range_picker","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'COLOR_PICKER', 'Color picker field', '{"input_type":"color_picker","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'CREDIT_CARD_FIELD', 'Credit card field', '{"input_type":"credit_card_field","options":{"include_expiry":true,"include_cvv":true}}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'FILE_UPLOAD', 'File upload field', '{"input_type":"file","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'MULTI_FILE_UPLOAD', 'Multiple file upload field', '{"input_type":"multi_file","options":null}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'FOREIGN_KEY', 'Foreign key field', '{"input_type":"foreign_key","related_table":"related_table_here","related_field":"related_field_here"}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'CSV_FOREIGN_KEYS', 'Comma-separated foreign keys field', '{"input_type":"csv_foreign_keys","related_table":"related_table_here","related_field":"related_field_here"}'),
(UUID(), '1', '0', '0', CURRENT_TIMESTAMP, 'CUSTOM_TYPE', 'Custom field type', '{"input_type":"custom","options":{}}');
